<?php
return array (
  'ad_pos.container_breadcrumb_bottom_above' => 'Выше нижнего контейнера хлебных крошек',
  'ad_pos.container_breadcrumb_bottom_below' => 'Ниже нижнего контейнера хлебных крошек',
  'ad_pos.container_breadcrumb_top_above' => 'Выше верхнего контейнера хлебных крошек',
  'ad_pos.container_breadcrumb_top_below' => 'Ниже верхнего контейнера хлебных крошек',
  'ad_pos.container_content_above' => 'Выше контейнера содержимого',
  'ad_pos.container_content_below' => 'Ниже контейнера содержимого',
  'ad_pos.container_header' => 'В контейнере "шапки"',
  'ad_pos.container_sidebar_above' => 'Выше контейнера боковой панели',
  'ad_pos.container_sidebar_below' => 'Ниже контейнера боковой панели',
  'ad_pos.container_sidenav_above' => 'Выше контейнера боковой навигации',
  'ad_pos.container_sidenav_below' => 'Ниже контейнера боковой навигации',
  'ad_pos.forum_overview_bottom' => 'Внизу при обзоре форума',
  'ad_pos.forum_overview_top' => 'Вверху при обзоре форума',
  'ad_pos.forum_view_above_node_list' => 'Выше списка узлов при просмотре форума',
  'ad_pos.forum_view_above_thread_list' => 'Выше списка тем при просмотре форума',
  'ad_pos.forum_view_below_node_list' => 'Ниже списка узлов при просмотре форума',
  'ad_pos.forum_view_below_stickies' => 'Ниже списка закреплённых тем при просмотре форума',
  'ad_pos.forum_view_below_thread_list' => 'Ниже списка тем при просмотре форума',
  'ad_pos.member_view_below_tabs' => 'Ниже вкладок при просмотре профиля пользователя',
  'ad_pos.post_above_content' => 'Выше содержимого при просмотре сообщения',
  'ad_pos.post_below_container' => 'Ниже контейнера сообщения',
  'ad_pos.post_below_content' => 'Ниже содержимого при просмотре сообщения',
  'ad_pos.thread_view_above_messages' => 'Выше списка сообщений при просмотре темы',
  'ad_pos.thread_view_below_messages' => 'Ниже списка сообщений при просмотре темы',
);