<?php
return array (
  'admin_permission.activitySummary' => 'Управление сводкой активности',
  'admin_permission.addOn' => 'Управление плагинами',
  'admin_permission.advertising' => 'Управление рекламой',
  'admin_permission.attachment' => 'Управление вложениями',
  'admin_permission.ban' => 'Управление блокировками',
  'admin_permission.bbCodeSmilie' => 'Управление BB-кодами и смайлами',
  'admin_permission.cron' => 'Управление заданиями планировщика',
  'admin_permission.help' => 'Управление страницами помощи',
  'admin_permission.import' => 'Импорт данных',
  'admin_permission.language' => 'Управление языками и фразами',
  'admin_permission.navigation' => 'Управление навигацией',
  'admin_permission.node' => 'Управление узлами',
  'admin_permission.notice' => 'Управление объявлениями',
  'admin_permission.option' => 'Управление настройками',
  'admin_permission.payment' => 'Управление платёжными шлюзами',
  'admin_permission.reaction' => 'Управление реакциями',
  'admin_permission.rebuildCache' => 'Перестроение кэшей',
  'admin_permission.style' => 'Управление стилями, настройками стилей, и шаблонами',
  'admin_permission.tags' => 'Управление тегами',
  'admin_permission.thread' => 'Управление темами и сообщениями',
  'admin_permission.trophy' => 'Управление трофеями',
  'admin_permission.upgradeXenForo' => 'Обновление XenForo',
  'admin_permission.uploadSPImages' => 'Upload images for style properties',
  'admin_permission.user' => 'Управление пользователями и модераторами',
  'admin_permission.userField' => 'Управление дополнительными полями пользователя',
  'admin_permission.userGroup' => 'Управление группами пользователей',
  'admin_permission.userUpgrade' => 'Управление повышениями прав пользователей',
  'admin_permission.viewLogs' => 'Просмотр журналов',
  'admin_permission.viewStatistics' => 'Просмотр статистики',
  'admin_permission.warning' => 'Управление предупреждениями',
  'admin_permission.widget' => 'Управление виджетами',
);