<?php
return array (
  'button.attach' => 'Прикрепить файлы',
  'button.cancel' => 'Отмена',
  'button.confirm' => 'Подтвердить',
  'button.copy' => 'Копировать',
  'button.delete' => 'Удалить',
  'button.edit' => 'Редактировать',
  'button.export' => 'Экспорт',
  'button.hide' => 'Скрыть',
  'button.import' => 'Импорт',
  'button.login' => 'Войти',
  'button.merge' => 'Объединить',
  'button.move' => 'Переместить',
  'button.preview' => 'Предпросмотр',
  'button.purchase' => 'Купить',
  'button.save' => 'Сохранить',
  'button.search' => 'Поиск',
  'button.show' => 'Показать',
  'button.sort' => 'Сортировка',
  'button.submit' => 'Отправить',
  'button.translate' => 'Перевести',
);