<?php
return array (
  'cookie_consent.cookie_description___crossTab' => 'Этот элемент локального хранилища используется для хранения информации, используемой для взаимодействия между вкладками, например, текущего маркера (токена) подделки межсайтовых запросов.',
  'cookie_consent.cookie_description_cacheKey' => 'Этот элемент локального хранилища используется для хранения ключа кэша, используемого для элементов автономного хранилища.',
  'cookie_consent.cookie_description_consent' => 'Этот файл cookie используется для хранения предпочтений пользователя в отношении согласия на использование файлов cookie.',
  'cookie_consent.cookie_description_csrf' => 'Этот файл cookie используется для хранения маркера (токена) подделки межсайтовых запросов пользователя, что не позволяет другим приложениям делать вредоносные запросы от имени пользователя.',
  'cookie_consent.cookie_description_dbWriteForced' => 'Этот файл cookie используется для указания того, что запрос должен быть выполнен с помощью сервера записи базы данных.',
  'cookie_consent.cookie_description_editorDisabled' => 'Этот элемент локального хранилища используется для хранения информации о том, включен или нет у пользователя полнофункциональный текстовый редактор.',
  'cookie_consent.cookie_description_emoji_usage' => 'Этот файл cookie используется для хранения информации о том, какие эмодзи пользователь недавно использовал при составлении (написании) сообщения.',
  'cookie_consent.cookie_description_fr_copied_html' => 'Этот элемент локального хранилища используется для хранения скопированного пользователем отформатированного текста при вставке в текстовый редактор.',
  'cookie_consent.cookie_description_fr_copied_text' => 'Этот элемент локального хранилища используется для хранения скопированного пользователем обычного текста при вставке в текстовый редактор.',
  'cookie_consent.cookie_description_from_search' => 'Этот файл cookie используется для отслеживания того, когда пользователь пришел на сайт из поисковой системы.',
  'cookie_consent.cookie_description_guestUsername' => 'Этот элемент локального хранилища используется для хранения гостевого имени пользователя.',
  'cookie_consent.cookie_description_inline_mod__wildcard' => 'Эти файлы cookie используются для хранения выбранных пользователем в данный момент элементов встроенной модерации.',
  'cookie_consent.cookie_description_language_id' => 'Этот файл cookie используется для хранения выбранного пользователем языка.',
  'cookie_consent.cookie_description_lbSidebarDisabled' => 'Этот элемент локального хранилища используется для хранения информации о том, переключил ли пользователь сайдбар лайтбокса.',
  'cookie_consent.cookie_description_ls' => 'Этот файл cookie используется для хранения содержимого локального хранилища пользователя в случае, если его браузер не поддерживает собственный механизм локального хранилища.',
  'cookie_consent.cookie_description_multiQuote_wildcard' => 'Эти элементы локального хранилища используются для хранения выбранных пользователем мультицитат.',
  'cookie_consent.cookie_description_notice_dismiss' => 'Этот файл cookie используется для хранения скрытых (отклонённых) пользователем объявлений.',
  'cookie_consent.cookie_description_push_history_user_ids' => 'Этот элемент локального хранилища используется для хранения данных о том, какие пользователи на данном устройстве включили push-уведомления.',
  'cookie_consent.cookie_description_push_notice_dismiss' => 'Этот файл cookie используется для определения того, отклонил ли пользователь push-уведомления.',
  'cookie_consent.cookie_description_push_subscription_updated' => 'Этот файл cookie используется для определения того, были ли обновлены предпочтения пользователя в отношении подписки на push.',
  'cookie_consent.cookie_description_session' => 'Этот файл cookie используется для хранения идентификатора (ID) сессии пользователя.',
  'cookie_consent.cookie_description_style_id' => 'Этот файл cookie используется для хранения выбранного пользователем стиля.',
  'cookie_consent.cookie_description_tfa_trust' => 'Этот файл cookie используется для определения того, решил ли пользователь ранее доверять данному устройству, не требуя дальнейшей двухэтапной проверки в течение определенного периода времени.',
  'cookie_consent.cookie_description_toggle' => 'Этот файл cookie и элемент локального хранилища используются для хранения предпочтений пользователя по открытию или закрытию различных элементов управления.',
  'cookie_consent.cookie_description_user' => 'Этот файл cookie используется для хранения маркера (токена) "запомнить меня" пользователя, что позволяет сохранять его учетные данные в течение нескольких сеансов и позволяет Вам оставаться авторизованным на сайте при перемещении со страницы на страницу.',
  'cookie_consent.cookie_description_visitorCounts' => 'Этот элемент локального хранилища используется для хранения счётчика непрочитанных переписок и оповещений пользователя.',
  'cookie_consent.group_description__required' => 'Эти файлы cookie необходимы для обеспечения основных функций, таких как безопасность, управление сетью и доступность. Вы не можете их отклонить.',
  'cookie_consent.group_description__third_party' => 'Cookies, установленные третьими сторонами, могут потребоваться для обеспечения функциональности совместно с различными поставщиками услуг в целях безопасности, аналитики, производительности или рекламы.',
  'cookie_consent.group_description_optional' => 'Мы предоставляем расширенные функциональные возможности для Вашего просмотра, устанавливая эти файлы cookie. Если Вы отклоните их, расширенная функциональность будет недоступна.',
  'cookie_consent.group_label__required' => 'Необходимые файлы cookie',
  'cookie_consent.group_label__third_party' => 'Сторонние файлы cookie',
  'cookie_consent.group_label_optional' => 'Необязательные файлы cookie',
  'cookie_consent.third_party_description_apple_music' => 'Эти файлы cookie устанавливаются <a href="https://www.apple.com/legal/privacy/data/en/apple-music/" target="_blank">Apple Music</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_braintree' => 'Эти файлы cookie устанавливаются <a href="https://www.braintreepayments.com/pl/legal/braintree-privacy-policy" target="_blank">Braintree</a> и могут использоваться для обработки платежей.',
  'cookie_consent.third_party_description_dailymotion' => 'Эти файлы cookie устанавливаются <a href="https://legal.dailymotion.com/en/privacy-policy/" target="_blank">Dailymotion</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_facebook' => 'Эти файлы cookie устанавливаются <a href="https://www.facebook.com/privacy/policy/" target="_blank">Facebook</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_flickr' => 'Эти файлы cookie устанавливаются <a href="https://www.flickr.com/help/privacy" target="_blank">Flickr</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_giphy' => 'Эти файлы cookie устанавливаются <a href="https://support.giphy.com/hc/en-us/articles/360032872931-GIPHY-Privacy-Policy" target="_blank">Giphy</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_google_analytics' => 'Эти файлы cookie устанавливаются <a href="https://policies.google.com/privacy" target="_blank">Google Analytics</a> и могут использоваться для аналитики.',
  'cookie_consent.third_party_description_google_recaptcha' => 'Эти файлы cookie устанавливаются <a href="https://policies.google.com/privacy" target="_blank">Google reCAPTCHA</a> и могут использоваться для проверки законного трафика.',
  'cookie_consent.third_party_description_h_captcha' => 'Эти файлы cookie устанавливаются <a href="https://www.hcaptcha.com/privacy" target="_blank">HCaptcha</a> и могут использоваться для проверки легальности трафика.',
  'cookie_consent.third_party_description_imgur' => 'Эти файлы cookie устанавливаются <a href="https://imgur.com/privacy" target="_blank">Imgur</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_instagram' => 'Эти файлы cookie устанавливаются <a href="https://www.facebook.com/privacy/policy/" target="_blank">Instagram</a> и могут использоваться для отображения встроенного содержимого. ',
  'cookie_consent.third_party_description_key_captcha' => 'Эти файлы cookie устанавливаются <a href="https://www.keycaptcha.com" target="_blank">KeyCaptcha</a> и могут использоваться для проверки законного трафика.',
  'cookie_consent.third_party_description_meta' => 'Эти файлы cookie устанавливаются <a href="https://www.facebook.com/privacy/policy/" target="_blank">Meta</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_pinterest' => 'Эти файлы cookie устанавливаются <a href="https://policy.pinterest.com/en/privacy-policy" target="_blank">Pinterest</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_reddit' => 'Эти файлы cookie устанавливаются <a href="https://www.reddit.com/policies/privacy-policy" target="_blank">Reddit</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_solve_media' => 'Эти файлы cookie устанавливаются <a href="https://www.solvemedia.com/privacy.html" target="_blank">SolveMedia</a> и могут использоваться для проверки законности трафика.',
  'cookie_consent.third_party_description_soundcloud' => 'Эти файлы cookie устанавливаются <a href="https://soundcloud.com/pages/privacy" target="_blank">SoundCloud</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_spotify' => 'Эти файлы cookie устанавливаются <a href="https://www.spotify.com/us/legal/privacy-policy/" target="_blank">Spotify</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_stripe' => 'Эти файлы cookie устанавливаются <a href="https://stripe.com/privacy" target="_blank">Stripe</a> и могут использоваться для обработки платежей.',
  'cookie_consent.third_party_description_tiktok' => 'Эти файлы cookie устанавливаются <a href="https://www.tiktok.com/legal/page/us/privacy-policy/en" target="_blank">TikTok</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_tumblr' => 'Эти файлы cookie устанавливаются <a href="https://www.tumblr.com/privacy" target="_blank">Tumblr</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_twitch' => 'Эти файлы cookie устанавливаются <a href="https://www.twitch.tv/p/en/legal/privacy-notice/" target="_blank">Twitch</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_twitter' => 'Эти файлы cookie устанавливаются <a href="https://twitter.com/privacy" target="_blank">Twitter</a> и могут использоваться для отображения встроенного содержимого.',
  'cookie_consent.third_party_description_two_checkout' => 'Эти файлы cookie устанавливаются <a href="https://www.2checkout.com/legal/privacy/" target="_blank">2Checkout</a> и могут использоваться для обработки платежей.',
  'cookie_consent.third_party_description_vimeo' => 'Эти файлы cookie устанавливаются <a href="https://vimeo.com/privacy" target="_blank">Vimeo</a> и могут использоваться для отображения встроенного контента.',
  'cookie_consent.third_party_description_youtube' => 'Эти файлы cookie устанавливаются <a href="https://policies.google.com/privacy" target="_blank">YouTube</a> и могут использоваться для аналитики, проверки законного трафика или другого встроенного содержимого.',
  'cookie_consent.third_party_label_apple_music' => 'Apple Music',
  'cookie_consent.third_party_label_braintree' => 'Braintree',
  'cookie_consent.third_party_label_dailymotion' => 'Dailymotion',
  'cookie_consent.third_party_label_facebook' => 'Facebook',
  'cookie_consent.third_party_label_flickr' => 'Flickr',
  'cookie_consent.third_party_label_giphy' => 'Giphy',
  'cookie_consent.third_party_label_google_analytics' => 'Google Analytics',
  'cookie_consent.third_party_label_google_recaptcha' => 'Google reCAPTCHA',
  'cookie_consent.third_party_label_h_captcha' => 'HCaptcha',
  'cookie_consent.third_party_label_imgur' => 'Imgur',
  'cookie_consent.third_party_label_instagram' => 'Instagram',
  'cookie_consent.third_party_label_key_captcha' => 'KeyCaptcha',
  'cookie_consent.third_party_label_meta' => 'Meta',
  'cookie_consent.third_party_label_pinterest' => 'Pinterest',
  'cookie_consent.third_party_label_reddit' => 'Reddit',
  'cookie_consent.third_party_label_solve_media' => 'SolveMedia',
  'cookie_consent.third_party_label_soundcloud' => 'SoundCloud',
  'cookie_consent.third_party_label_spotify' => 'Spotify',
  'cookie_consent.third_party_label_stripe' => 'Stripe',
  'cookie_consent.third_party_label_tiktok' => 'TikTok',
  'cookie_consent.third_party_label_tumblr' => 'Tumblr',
  'cookie_consent.third_party_label_twitch' => 'Twitch',
  'cookie_consent.third_party_label_twitter' => 'Twitter',
  'cookie_consent.third_party_label_two_checkout' => '2Checkout',
  'cookie_consent.third_party_label_vimeo' => 'Vimeo',
  'cookie_consent.third_party_label_youtube' => 'YouTube',
);