<?php
return array (
  'cron_entry.activitySummaryEmail' => 'Отправка электронных писем со сводкой активности',
  'cron_entry.cleanUpDaily' => 'Ежедневная очистка',
  'cron_entry.cleanUpHourly' => 'Ежечасная очистка',
  'cron_entry.dailyStats' => 'Запись ежедневной статистики',
  'cron_entry.deleteExpiredBans' => 'Удаление истёкших блокировок',
  'cron_entry.downgradeExpired' => 'Обработка истёкших платных повышений прав пользователей',
  'cron_entry.emailBounce' => 'Обработка отказов в доставке почты',
  'cron_entry.emailUnsubscribe' => 'Отправка запросов на отмену email-рассылки',
  'cron_entry.expireTempUserChanges' => 'Обработка истёкших временных изменений пользователя',
  'cron_entry.feeder' => 'Ленты сообщений',
  'cron_entry.fileCheck' => 'Выполнение проверки целостности файлов',
  'cron_entry.forumStatistics' => 'Перестроение статистики форума',
  'cron_entry.memberStatsCache' => 'Перестроение кэшей статистики пользователей',
  'cron_entry.rebuildSearchForumCache' => 'Перестроение истёкших кэшей форумов для поиска',
  'cron_entry.run_successfully' => 'Задание планировщика было выполнено без ошибок.',
  'cron_entry.sitemap' => 'Перестроение карты сайта',
  'cron_entry.th_updateCheck_uix' => '[TH] UI.X: Check for updates',
  'cron_entry.trophy' => 'Обновление трофеев пользователей',
  'cron_entry.userGroupPromotions' => 'Повышения групп пользователей',
  'cron_entry.views' => 'Обновление счётчиков просмотров',
  'cron_entry.warningExpiry' => 'Обработка истёкших предупреждений',
);