<?php
return array (
  'nav._default' => 'По умолчанию (без выбранной вкладки)',
  'nav.contributedThreads' => 'Темы с моими сообщениями',
  'nav.currentVisitors' => 'Текущие посетители',
  'nav.defaultLatestActivity' => 'Последняя активность',
  'nav.defaultLogOut' => 'Выход',
  'nav.defaultNewsFeed' => 'Ваша новостная лента',
  'nav.defaultRegister' => 'Регистрация',
  'nav.defaultYourAccount' => 'Ваша учётная запись',
  'nav.defaultYourProfile' => 'Ваш профиль',
  'nav.findThreads' => 'Найти темы',
  'nav.forumList' => 'Список форумов',
  'nav.forums' => 'Форумы',
  'nav.home' => 'Главная',
  'nav.latestActivity' => 'Последняя активность',
  'nav.markForumsRead' => 'Отметить форумы прочитанными',
  'nav.members' => 'Пользователи',
  'nav.newPosts' => 'Новые сообщения',
  'nav.newProfilePosts' => 'Новые сообщения профилей',
  'nav.registeredMembers' => 'Зарегистрированные пользователи',
  'nav.searchForums' => 'Поиск сообщений',
  'nav.searchProfilePosts' => 'Поиск сообщений профилей',
  'nav.unansweredThreads' => 'Темы без ответов',
  'nav.watched' => 'Отслеживаемое',
  'nav.watchedForums' => 'Отслеживаемые форумы',
  'nav.watchedThreads' => 'Отслеживаемые темы',
  'nav.whatsNew' => 'Что нового?',
  'nav.whatsNewNewsFeed' => 'Ваша новостная лента',
  'nav.whatsNewPosts' => 'Новые сообщения',
  'nav.whatsNewProfilePosts' => 'Новые сообщения профилей',
  'nav.yourThreads' => 'Мои темы',
);