<?php
return array (
  'option_group_description.acp' => 'Содержит различные настройки, связанные непосредственно с панелью управления.',
  'option_group_description.alerts' => 'Когда происходит событие, имеющее значение для конкретного пользователя, он будет уведомлён с использованием данной системы. Со временем, старые оповещения удаляются из базы данных.',
  'option_group_description.appearance' => 'Эти настройки управляют тем, как Ваш форум будет отображаться посетителям.',
  'option_group_description.attachments' => 'Вложения - это файлы, которые пользователи могут загружать на форум и прикреплять к сообщениям.',
  'option_group_description.basicBoard' => '',
  'option_group_description.boardActive' => 'Здесь Вы можете включить или отключить форум.',
  'option_group_description.censoringOptions' => 'Текст, который размещают пользователи, будет подвергаться цензуре по правилам, которые Вы укажете здесь.',
  'option_group_description.debug' => 'Эти настройки предназначены исключительно для разработчиков XenForo.',
  'option_group_description.discourager' => 'Нежелательные пользователи - система, которая стремится сделать посещение и просмотр форума для "проблемных" пользователей затруднительным. Целью является их уход с сайта "естественным" способом.<br />
<br />
Вы можете включить режим "Нежелательный пользователь" в настройках учётной записи пользователя или добавить IP или диапазон IP к нежелательным.',
  'option_group_description.discussionOptions' => 'Эти настройки распространяются на все сообщения, размещаемые на форуме - в темах, профилях, личных переписках и так далее.',
  'option_group_description.emailOptions' => '',
  'option_group_description.imageLinkProxy' => 'Управление системой проксирования и журналами размещаемых ссылок, и изображений.',
  'option_group_description.logging' => 'Настройки, контролирующие какие данные должны быть записаны и как долго они должны храниться.',
  'option_group_description.mediaEmbedding' => 'Настройки вставки внешних медиа, таких как видео, аудиоклипы и контент из социальных сетей.',
  'option_group_description.messageOptions' => 'Эти настройки распространяются на все сообщения, размещаемые на форуме - в темах, профилях, личной переписке и так далее.',
  'option_group_description.newsfeed' => 'Новостные ленты или ленты активности - это постоянно обновляемый журнал, в который записываются действия зарегистрированных пользователей и который могут просматривать другие посетители.<br>
<br>
Новостные ленты можно фильтровать, чтобы видеть действия только тех пользователей, чьими подписчиками Вы являетесь, или действия одного пользователя.',
  'option_group_description.nodeList' => 'Узлы и список форумов являются основной структурой навигации для форумов и страниц.',
  'option_group_description.performance' => 'Настройки производительности Вашего форума.',
  'option_group_description.pwa' => 'Помощник настройки PWA',
  'option_group_description.searchOptions' => 'Настройки системы поиска, встроенной в XenForo, позволяющей искать сообщения и другое содержимое.',
  'option_group_description.seo' => 'На этой странице Вы можете настраивать параметры конструирования ссылок и отображения содержания форума.',
  'option_group_description.serviceProviders' => 'Для некоторых функций, XenForo будет передавать информацию третьим лицам в виде поставщиков служб. Здесь можно изменить некоторые параметры, используемые по умолчанию.',
  'option_group_description.sharing' => 'Возможность делиться публикациями с форума в социальных сетях.',
  'option_group_description.sitemap' => 'Эти настройки позволяют контролировать генерирование XML-карты сайта и её отправки поисковым системам. Карта может быть использована для ускорения поисковой индексации Вашего форума.',
  'option_group_description.spam' => 'Настройки по умолчанию для очистки спама и системы его предотвращения.',
  'option_group_description.stats' => '',
  'option_group_description.tagging' => 'Настройки, контролирующие применение тегов к содержимому.',
  'option_group_description.th_uix' => 'Options in this group allow you to customize your UI.X experience.',
  'option_group_description.users' => '',
  'option_group_description.usersAndRegistration' => '',
  'option_group_description.xentr_newTicker' => 'Those options are control the News Ticker.',
  'option_group_description.xentr_styleProperties' => 'Those options are control the XenTR style properties',
  'option_group_description.xentr_userReactions' => 'Those options are control the XenTR user reactions.',
  'option_group_description.xmStyleProperty' => 'Customizable and advanced style features options.',
);