<?php
return array (
  'style_prop_group.avatar' => 'Аватары',
  'style_prop_group.basic' => 'Основные настройки',
  'style_prop_group.bbCode' => 'Элементы BB-кодов',
  'style_prop_group.block' => 'Блоки',
  'style_prop_group.borderSpacing' => 'Границы и расстояния',
  'style_prop_group.button' => 'Кнопки',
  'style_prop_group.color' => 'Основные цвета',
  'style_prop_group.content' => 'Области содержимого',
  'style_prop_group.dataList' => 'Списки данных',
  'style_prop_group.email' => 'Электронные письма',
  'style_prop_group.fonts' => 'Типография',
  'style_prop_group.footer' => 'Подвал',
  'style_prop_group.form' => 'Формы',
  'style_prop_group.headerNav' => 'Шапка и навигация',
  'style_prop_group.inlineMod' => 'Модерация',
  'style_prop_group.input' => 'Ввод данных',
  'style_prop_group.member' => 'Профили пользователей',
  'style_prop_group.menu' => 'Всплывающие меню',
  'style_prop_group.message' => 'Сообщения',
  'style_prop_group.misc' => 'Прочее',
  'style_prop_group.nodeList' => 'Список узлов/форумов',
  'style_prop_group.overlay' => 'Всплывающие окна',
  'style_prop_group.page' => 'Настройки страницы',
  'style_prop_group.palette' => 'Цветовая палитра',
  'style_prop_group.rte' => 'Полнофункциональный текстовый редактор',
  'style_prop_group.tab' => 'Вкладки',
  'style_prop_group.th_uix_staffMessages' => 'Staff messages',
  'style_prop_group.th_uix_threadStarterMessages' => 'Thread starter messages',
  'style_prop_group.tooltip' => 'Всплывающие подсказки',
);