<?php
return array (
  'widget_def.birthdays' => 'Сегодняшние именинники',
  'widget_def.dcs_next_group' => '[DevCore Studios] Next Group',
  'widget_def.find_member' => 'Найти пользователя',
  'widget_def.forum_statistics' => 'Статистика форума',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Статистика пользователей',
  'widget_def.members_online' => 'Пользователи онлайн',
  'widget_def.new_posts' => 'Новые сообщения',
  'widget_def.new_profile_posts' => 'Сообщения профилей',
  'widget_def.new_threads' => 'Новые темы',
  'widget_def.newest_members' => 'Новые пользователи',
  'widget_def.online_statistics' => 'Онлайн статистика',
  'widget_def.php_callback' => 'PHP-обработчик',
  'widget_def.search_forum' => 'Форум для поиска',
  'widget_def.share_page' => 'Поделиться страницей',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_post_thread_uix' => '[UI.X] Start a thread',
  'widget_def.th_widget_login_uix' => '[UI.X] Login form',
  'widget_def.thread_poll' => 'Опрос',
  'widget_def.thuix_socialMedia' => '[TH] UI.X social media feed',
  'widget_def.visitor_panel' => 'Панель посетителя',
  'widget_def.xentr_newsTicker_widget' => '[XTR] Style Properties-NewsTicker',
);