<?php
return array (
  'widget_def_desc.birthdays' => 'Блок, содержащий аватары пользователей, которые сегодня отмечают свой день рождения.',
  'widget_def_desc.dcs_next_group' => '',
  'widget_def_desc.find_member' => 'Добавляет на страницу блок с поддержкой авто-заполнения, который позволяет Вам найти профиль пользователя по его имени.',
  'widget_def_desc.forum_statistics' => 'Отображает блок, который показывает текущую статистику форума по таким параметрам, как общее количество тем, сообщений и пользователей.',
  'widget_def_desc.html' => 'Виджет, который позволяет добавлять пользовательский HTML-код. Этот виджет поддерживает синтаксис шаблонов XenForo.',
  'widget_def_desc.member_stat' => 'Отображение списка пользователей с выбранной статистикой.',
  'widget_def_desc.members_online' => 'Отображает сводную информацию о количестве онлайн-пользователей, гостей и роботов, а также общее количество онлайн-пользователей и людей, на которых Вы подписаны.',
  'widget_def_desc.new_posts' => 'Отображает блок, содержащий список Х тем, в которых недавно были размещены новые сообщения.',
  'widget_def_desc.new_profile_posts' => 'Отображает блок, содержащий список последних X сообщений профилей.',
  'widget_def_desc.new_threads' => 'Отображает блок, содержащий список X последних тем.',
  'widget_def_desc.newest_members' => 'Блок, содержащий аватары последних зарегистрированных пользователей.',
  'widget_def_desc.online_statistics' => 'Отображает блок статистики с разбивкой по текущим посетителям форума и независимо от того, являются они зарегистрированными, гостями или роботами.',
  'widget_def_desc.php_callback' => 'Возможность отображения содержимого виджета с помощью PHP-обработчика. Обработчик должен возвращать объект \\XF\\Widget\\WidgetRenderer, настроенный с именем шаблона и параметрами, необходимыми для визуализации виджета.',
  'widget_def_desc.search_forum' => 'Отображает блок, содержащий список X тем из форума для поиска.',
  'widget_def_desc.share_page' => 'Блок кнопок социальных сетей, используя которые пользователи смогут поделиться понравившейся им страницей.',
  'widget_def_desc.template_syntax' => 'Виджет создаёт связанный шаблон, который позволит Вам отобразить синтаксис шаблона XF и HTML.',
  'widget_def_desc.th_post_thread_uix' => 'Allows you to display a post new thread block in your sidebar',
  'widget_def_desc.th_widget_login_uix' => 'Allows you to display a login bar in your sidebar, or any other widget location.',
  'widget_def_desc.thread_poll' => 'Отображение указанного опроса в виджете.',
  'widget_def_desc.thuix_socialMedia' => '',
  'widget_def_desc.visitor_panel' => 'Отображение аватара посетителя и основной информации о нём.',
  'widget_def_desc.xentr_newsTicker_widget' => 'Displays a ticker block containing a list of X threads which have most recently been created.',
);