<?php
return array (
  'widget_pos.category_view_sidebar' => 'Просмотр категории: боковая панель',
  'widget_pos.conversation_list_sidebar' => 'Список переписок: боковая панель',
  'widget_pos.conversation_view_sidebar' => 'Просмотр переписки: боковая панель',
  'widget_pos.find_threads_sidenav' => 'Поиск тем: боковая навигация',
  'widget_pos.forum_list_above_nodes' => 'Список форумов: выше списка узлов',
  'widget_pos.forum_list_below_nodes' => 'Список форумов: ниже списка узлов',
  'widget_pos.forum_list_sidebar' => 'Список форумов: боковая панель',
  'widget_pos.forum_new_posts_sidebar' => 'Новые сообщения форума: боковая панель',
  'widget_pos.forum_overview_bottom' => 'Обзор форума: низ',
  'widget_pos.forum_overview_top' => 'Обзор форума: верх',
  'widget_pos.forum_view_sidebar' => 'Просмотр форума: боковая панель',
  'widget_pos.help_page_sidenav' => 'Страница помощи: боковая навигация',
  'widget_pos.member_view_sidebar' => 'Страница профиля пользователя: боковая панель',
  'widget_pos.member_wrapper_sidenav' => 'Пользователи: боковая навигация',
  'widget_pos.online_list_sidebar' => 'Список онлайн: боковая панель',
  'widget_pos.pub_sidebar_bottom' => 'Публичная часть: внизу боковой панели',
  'widget_pos.pub_sidebar_top' => 'Публичная часть: вверху боковой панели',
  'widget_pos.th_footer_uix' => 'UI.X: Extended footer',
  'widget_pos.th_sidebarNavigation_uix' => 'UI.X: Sidebar navigation',
  'widget_pos.thread_view_above_messages' => 'Просмотр темы: над сообщениями',
  'widget_pos.thread_view_below_messages' => 'Просмотр темы: под сообщениями',
  'widget_pos.thread_view_below_quick_reply' => 'Просмотр темы: ниже формы быстрого ответа',
  'widget_pos.thread_view_sidebar' => 'Просмотр темы: боковая панель',
  'widget_pos.thuix_index_page' => 'Forums default page: Sidebar',
  'widget_pos.whats_new_overview' => 'Что нового?: обзор',
  'widget_pos.whats_new_sidenav' => 'Что нового?: боковая навигация',
);