<?php
return array (
  'widget_pos_desc.category_view_sidebar' => 'Позиция в боковой панели шаблона category_view. Шаблоны виджетов, отображаемые в этой позиции, могут использовать объект текущей категории в параметре <code>{$context.category}</code>. Эти виджеты будут видны только в том случае, если включена опция "Создавать страницы для категорий".',
  'widget_pos_desc.conversation_list_sidebar' => 'Позиция в боковой панели при просмотре списка переписок.',
  'widget_pos_desc.conversation_view_sidebar' => 'Позиция в боковой панели шаблона conversation_view. Шаблоны виджетов, отображаемые в этой позиции, могут использовать объект текущей переписки в параметре <code>{$context.conversation}</code>.',
  'widget_pos_desc.find_threads_sidenav' => 'Position inside the \'find threads\' side navigation, which is shown only when <i>Appearance &gt; Style properties &gt; Miscellaneous &gt; Find threads navigation style</i> is set to \'Side navigation\'.',
  'widget_pos_desc.forum_list_above_nodes' => 'A position inside the main content area of the forum list above the node tree.',
  'widget_pos_desc.forum_list_below_nodes' => 'A position inside the main content area of the forum list below the node tree.',
  'widget_pos_desc.forum_list_sidebar' => 'Позиция в боковой панели списка форумов для отображения различной статистики и виджетов с новым содержимым.',
  'widget_pos_desc.forum_new_posts_sidebar' => 'Позиция в боковой панели на странице "Новые сообщения" для отображения различной статистики и виджетов с новым содержимым. Примечание: эта страница будет доступна только в том случае, если по умолчанию страницей для форума будет являться ”Новые сообщения”.',
  'widget_pos_desc.forum_overview_bottom' => 'Отображение в нижней части обзора форума, ниже содержимого списка форумов и вкладки "Новые сообщения", если она установлена в качестве целевой страницы форума по умолчанию.',
  'widget_pos_desc.forum_overview_top' => 'Отображение в верхней части обзора форума, выше содержимого списка форумов и вкладки "Новые сообщения", если она установлена в качестве целевой страницы форума по умолчанию.',
  'widget_pos_desc.forum_view_sidebar' => 'Позиция в боковой панели при просмотре списка тем или подфорумов в форуме. Шаблоны виджетов, отображаемые в этой позиции, могут использовать объект текущего форума в параметре <code>{$context.forum}</code>.',
  'widget_pos_desc.help_page_sidenav' => 'Position inside the Help sidenav, below the navigation block. Widgets here will appear off canvas on narrow displays.',
  'widget_pos_desc.member_view_sidebar' => 'Позиция в боковой панели при просмотре профиля пользователя. Шаблоны виджетов, отображаемые в этой позиции, могут использовать объект текущего пользователя в параметре <code>{$context.user}</code>.',
  'widget_pos_desc.member_wrapper_sidenav' => 'Отображение в боковой навигации внутри шаблонов, связанных с пользователями. Например, на страницах: "Полезные пользователи" и "Зарегистрированные пользователи".',
  'widget_pos_desc.online_list_sidebar' => 'Позиция внутри боковой панели шаблона online_list для отображения различной статистики 
 на странице "Текущие посетители".',
  'widget_pos_desc.pub_sidebar_bottom' => 'Widget position that appears at the bottom of all public pages. Page specific widgets will always appear above this position.',
  'widget_pos_desc.pub_sidebar_top' => 'Widget position that appears at the top of all public pages. Page specific widgets will always appear below this position.',
  'widget_pos_desc.th_footer_uix' => '',
  'widget_pos_desc.th_sidebarNavigation_uix' => '',
  'widget_pos_desc.thread_view_above_messages' => 'Позиция в основной области содержимого при просмотре темы, над сообщениями. Шаблоны виджетов, отображаемые в этой позиции, могут использовать текущий параметр элемента темы - <code>{$context.thread}</code>.',
  'widget_pos_desc.thread_view_below_messages' => 'Позиция в основной области содержимого при просмотре темы, под сообщениями. Шаблоны виджетов, отображаемые в этой позиции, могут использовать текущий параметр элемента темы - <code>{$context.thread}</code>.',
  'widget_pos_desc.thread_view_below_quick_reply' => 'Позиция в основной области содержимого при просмотре темы, ниже формы быстрого ответа. Шаблоны виджетов, отображаемые в этой позиции, могут использовать текущий параметр элемента темы - <code>{$context.thread}</code>.',
  'widget_pos_desc.thread_view_sidebar' => 'Позиция в боковой панели при просмотре темы. Шаблоны виджетов, отображаемые в этой позиции, могут использовать объект текущей темы в параметре <code>{$context.thread}</code>.',
  'widget_pos_desc.thuix_index_page' => 'Position in the sidebar while viewing the forums default page.',
  'widget_pos_desc.whats_new_overview' => 'Позиция внутри шаблона whats_new для отображения новых и недавних событий. Это занимает основную колонку, поэтому может поддерживать более большие виджеты.',
  'widget_pos_desc.whats_new_sidenav' => 'Position inside the What\'s new sidenav, below the navigation block. Widgets here will appear off canvas on narrow displays. Only applicable if the side navigation option is selected for the "What\'s new navigation style" style property.',
);