<?php
return array (
  'cookie_consent.cookie_description___crossTab' => 'This local storage item is used to store information used to communicate across tabs, such as the current cross-site request forgery token.',
  'cookie_consent.cookie_description_cacheKey' => 'This local storage item is used to store the cache key used for offline storage items.',
  'cookie_consent.cookie_description_consent' => 'This cookie is used to store a user\'s cookie consent preferences.',
  'cookie_consent.cookie_description_csrf' => 'This cookie is used to store a user\'s cross-site request forgery token, preventing other applications from making malicious requests on the user\'s behalf.',
  'cookie_consent.cookie_description_dbWriteForced' => 'This cookie is used to indicate that the request should be completed using the write-only database server.',
  'cookie_consent.cookie_description_editorDisabled' => 'This local storage item is used to store whether or not a user has the rich text editor enabled.',
  'cookie_consent.cookie_description_emoji_usage' => 'This cookie is used to store which emojis a user has recently used when composing a message.',
  'cookie_consent.cookie_description_fr_copied_html' => 'This local storage item is used to store a user\'s copied rich text when pasting into the text editor.',
  'cookie_consent.cookie_description_fr_copied_text' => 'This local storage item is used to store a user\'s copied plain text when pasting into the text editor.',
  'cookie_consent.cookie_description_from_search' => 'This cookie is used to track when a user has arrived on the site from a search engine.',
  'cookie_consent.cookie_description_guestUsername' => 'This local storage item is used to store a guest user\'s username.',
  'cookie_consent.cookie_description_inline_mod__wildcard' => 'These cookies are used to store a user\'s currently selected inline moderation items.',
  'cookie_consent.cookie_description_language_id' => 'This cookie is used to store a user\'s selected language.',
  'cookie_consent.cookie_description_lbSidebarDisabled' => 'This local storage item is used to store whether or not a user has toggled the lightbox sidebar.',
  'cookie_consent.cookie_description_ls' => 'This cookie is used to store a user\'s local storage contents in the event their browser does not support the native local storage mechanism.',
  'cookie_consent.cookie_description_multiQuote_wildcard' => 'These local storage items are used to store a user\'s multi-quote selections.',
  'cookie_consent.cookie_description_notice_dismiss' => 'This cookie is used to store a user\'s dismissed notices.',
  'cookie_consent.cookie_description_push_history_user_ids' => 'This local storage item is used to store which users on this device have enabled push notifications.',
  'cookie_consent.cookie_description_push_notice_dismiss' => 'This cookie is used to determine whether or not a user has dismissed the push notification notice.',
  'cookie_consent.cookie_description_push_subscription_updated' => 'This cookie is used to determine if a user\'s push subscription preferences have been updated.',
  'cookie_consent.cookie_description_session' => 'This cookie is used to store a user\'s session identifier.',
  'cookie_consent.cookie_description_style_id' => 'This cookie is used to store a user\'s selected style.',
  'cookie_consent.cookie_description_tfa_trust' => 'This cookie is used to determine if a user has previously chosen to trust this device without requiring further two-step verification for a period of time.',
  'cookie_consent.cookie_description_toggle' => 'This cookie and local storage item are used to store a user\'s preferences for toggling various controls open or closed.',
  'cookie_consent.cookie_description_user' => 'This cookie is used to store a user\'s "remember me" token, allowing their credentials to persist across multiple sessions.',
  'cookie_consent.cookie_description_visitorCounts' => 'This local storage item is used to store counts of a user\'s unread conversations and alerts.',
  'cookie_consent.group_description__required' => 'These cookies are required to enable core functionality such as security, network management, and accessibility. You may not reject these.',
  'cookie_consent.group_description__third_party' => 'Cookies set by third parties may be required to power functionality in conjunction with various service providers for security, analytics, performance or advertising purposes.',
  'cookie_consent.group_description_optional' => 'We deliver enhanced functionality for your browsing experience by setting these cookies. If you reject them, enhanced functionality will be unavailable.',
  'cookie_consent.group_label__required' => 'Essential cookies',
  'cookie_consent.group_label__third_party' => 'Third-party cookies',
  'cookie_consent.group_label_optional' => 'Optional cookies',
  'cookie_consent.third_party_description_apple_music' => 'These cookies are set by <a href="https://www.apple.com/legal/privacy/data/en/apple-music/" target="_blank">Apple Music</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_braintree' => 'These cookies are set by <a href="https://www.braintreepayments.com/pl/legal/braintree-privacy-policy" target="_blank">Braintree</a>, and may be used for processing payments.',
  'cookie_consent.third_party_description_dailymotion' => 'These cookies are set by <a href="https://legal.dailymotion.com/en/privacy-policy/" target="_blank">Dailymotion</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_facebook' => 'These cookies are set by <a href="https://www.facebook.com/privacy/policy/" target="_blank">Facebook</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_flickr' => 'These cookies are set by <a href="https://www.flickr.com/help/privacy" target="_blank">Flickr</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_giphy' => 'These cookies are set by <a href="https://support.giphy.com/hc/en-us/articles/360032872931-GIPHY-Privacy-Policy" target="_blank">Giphy</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_google_analytics' => 'These cookies are set by <a href="https://policies.google.com/privacy" target="_blank">Google Analytics</a>, and may be used for analytics.',
  'cookie_consent.third_party_description_google_recaptcha' => 'These cookies are set by <a href="https://policies.google.com/privacy" target="_blank">Google reCAPTCHA</a>, and may be used for verifying legitimate traffic.',
  'cookie_consent.third_party_description_h_captcha' => 'These cookies are set by <a href="https://www.hcaptcha.com/privacy" target="_blank">HCaptcha</a>, and may be used for verifying legitimate traffic.',
  'cookie_consent.third_party_description_imgur' => 'These cookies are set by <a href="https://imgur.com/privacy" target="_blank">Imgur</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_instagram' => 'These cookies are set by <a href="https://www.facebook.com/privacy/policy/" target="_blank">Instagram</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_key_captcha' => 'These cookies are set by <a href="https://www.keycaptcha.com" target="_blank">KeyCaptcha</a>, and may be used for verifying legitimate traffic.',
  'cookie_consent.third_party_description_meta' => 'These cookies are set by <a href="https://www.facebook.com/privacy/policy/" target="_blank">Meta</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_pinterest' => 'These cookies are set by <a href="https://policy.pinterest.com/en/privacy-policy" target="_blank">Pinterest</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_reddit' => 'These cookies are set by <a href="https://www.reddit.com/policies/privacy-policy" target="_blank">Reddit</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_solve_media' => 'These cookies are set by <a href="https://www.solvemedia.com/privacy.html" target="_blank">SolveMedia</a>, and may be used for verifying legitimate traffic.',
  'cookie_consent.third_party_description_soundcloud' => 'These cookies are set by <a href="https://soundcloud.com/pages/privacy" target="_blank">SoundCloud</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_spotify' => 'These cookies are set by <a href="https://www.spotify.com/us/legal/privacy-policy/" target="_blank">Spotify</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_stripe' => 'These cookies are set by <a href="https://stripe.com/privacy" target="_blank">Stripe</a>, and may be used for processing payments.',
  'cookie_consent.third_party_description_tiktok' => 'These cookies are set by <a href="https://www.tiktok.com/legal/page/us/privacy-policy/en" target="_blank">TikTok</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_tumblr' => 'These cookies are set by <a href="https://www.tumblr.com/privacy" target="_blank">Tumblr</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_twitch' => 'These cookies are set by <a href="https://www.twitch.tv/p/en/legal/privacy-notice/" target="_blank">Twitch</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_twitter' => 'These cookies are set by <a href="https://twitter.com/privacy" target="_blank">Twitter</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_two_checkout' => 'These cookies are set by <a href="https://www.2checkout.com/legal/privacy/" target="_blank">2Checkout</a>, and may be used for processing payments.',
  'cookie_consent.third_party_description_vimeo' => 'These cookies are set by <a href="https://vimeo.com/privacy" target="_blank">Vimeo</a>, and may be used for displaying embedded content.',
  'cookie_consent.third_party_description_youtube' => 'These cookies are set by <a href="https://policies.google.com/privacy" target="_blank">YouTube</a>, and may be used for analytics, verifying legitimate traffic, or other embedded content.',
  'cookie_consent.third_party_label_apple_music' => 'Apple Music',
  'cookie_consent.third_party_label_braintree' => 'Braintree',
  'cookie_consent.third_party_label_dailymotion' => 'Dailymotion',
  'cookie_consent.third_party_label_facebook' => 'Facebook',
  'cookie_consent.third_party_label_flickr' => 'Flickr',
  'cookie_consent.third_party_label_giphy' => 'Giphy',
  'cookie_consent.third_party_label_google_analytics' => 'Google Analytics',
  'cookie_consent.third_party_label_google_recaptcha' => 'Google reCAPTCHA',
  'cookie_consent.third_party_label_h_captcha' => 'HCaptcha',
  'cookie_consent.third_party_label_imgur' => 'Imgur',
  'cookie_consent.third_party_label_instagram' => 'Instagram',
  'cookie_consent.third_party_label_key_captcha' => 'KeyCaptcha',
  'cookie_consent.third_party_label_meta' => 'Meta',
  'cookie_consent.third_party_label_pinterest' => 'Pinterest',
  'cookie_consent.third_party_label_reddit' => 'Reddit',
  'cookie_consent.third_party_label_solve_media' => 'SolveMedia',
  'cookie_consent.third_party_label_soundcloud' => 'SoundCloud',
  'cookie_consent.third_party_label_spotify' => 'Spotify',
  'cookie_consent.third_party_label_stripe' => 'Stripe',
  'cookie_consent.third_party_label_tiktok' => 'TikTok',
  'cookie_consent.third_party_label_tumblr' => 'Tumblr',
  'cookie_consent.third_party_label_twitch' => 'Twitch',
  'cookie_consent.third_party_label_twitter' => 'Twitter',
  'cookie_consent.third_party_label_two_checkout' => '2Checkout',
  'cookie_consent.third_party_label_vimeo' => 'Vimeo',
  'cookie_consent.third_party_label_youtube' => 'YouTube',
);